### PR TITLE
Add converter script for sqlite database files.

### PR DESCRIPTION
**Pull request by sofar**
This script can convert back and forward between auth.sqlite and sauth.sqlite formats. It creates a new sqlite file (never overwriting an existing output file) and copies the auth entries over from the input format to the output format.

### CODE REVIEW

**Comment by shivajiva101** [comment]
The python script isn't pretty(semicolons, always returns 0 even with errors, concatenation instead of f-strings ) although it is functional, I actually gave up after 4 hours of processing my 148MB sauth database on a SSD drive, so its usage is realistically going to be for db's with less than 50k of entries or some hair pulling will occur. To that end I'll create a sql file to process the db quicker than this script when I code the shift in databases, so offline time is reduced to a minimum. See https://github.com/shivajiva101/sauth/issues/16#issuecomment-1451761953. Meantime any way to speed the script up?

**Comment by sofar** [comment]
Yeah, We can make a very large INSERT statement, with multiple values, and that'll be a single DB commit, instead of one per ID. Or one insert per $some_large_number or something.

**Comment by sofar** [comment]
Also, python is like dead last on my list of skills when it comes to programming languages, so, treat it as the garbage pile that it is :)

**Comment by shivajiva101** [comment]
Can you take a look at https://github.com/shivajiva101/sauth/tree/dev-0.5 and more specifically https://github.com/shivajiva101/sauth/blob/dev-0.5/tools/auth-convert.py
then let me know what you want to do about this pr in light of that?

**Comment by shivajiva101** [comment]
I'll take the lack of response as validation to close the pr. It's under baked and has poor performance unfortunately.

**Pull request closed without merging**
